### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by paliaksvk** [Dragorn421/ACMV#1]
Hello, I set everything as instructed, but when I enter the name and region, the page is loading, but does not display champion mastery. What is wrong?
My base.php
```
<?php
function getApiKey()
{
	return 'myRiotAPIKey';
}

function getDatabase()
{
	global $db;
	if(isset($db))
		return $db;
	try {
		$db = new PDO('mysql:host=myhost;dbname=myDBname', 'myDBusername', 'myDBpass');
	} catch(Exception $e) {
		exit('Exception: ' . $e->getMessage());
	}
	return $db;
}

function getEndpoints()
{
	return ['br'=>'BR1',
			'eune'=>'EUN1',
			'euw'=>'EUW1',
			'jp'=>'JP1',
			'kr'=>'KR',
			'lan'=>'LA1',
			'las'=>'LA2',
			'na'=>'NA1',
			'oce'=>'OC1',
			'ru'=>'RU',
			'tr'=>'TR1'];
}

function requestAPI($url)
{
	$tryCount = 0;
	do {
		$res = file_get_contents($url);
		$responseCode = intval(explode(' ', $http_response_header[0])[1]);
		if($responseCode == 200)
			return json_decode($res, TRUE);
		if($responseCode == 400 || $responseCode == 404)
			return NULL;
		if($responseCode == 429)
		{
			$wait = 10;
			foreach($http_response_header as $header)
				if(startsWith($header, 'Retry-After: '))
					$wait = intval(explode(' ', $header)[1]);
			sleep($wait);
		}
		$tryCount++;
	} while($tryCount != 5);
	return NULL;
}
?>
```
Thanks

**Comment by Dragorn421** [comment]
Not sure, check your logs, and use the javascript console to check if the ajax call to getMasteries.php failed in some way. What region and user are you requesting? Have you some way of sending me your current table setup?
Try it on my [live version here](http://brallos.tk/lol/acmv/), if it works there then either there's a problem with current github code (which is not up-to-date at the moment), or you setup the database/table wrong.
For the PDO creation i append `;charset=utf8` at the end of the first argument, you may try to add that, I don't believe that will do much of a difference.
And, I'm curious, why are you trying to replicate this? It doesn't bother me (keep in mind this is under the MIT license), but I don't get the point as there already is a live version.

**Comment by Dragorn421** [comment]
Just pushed a newer version, almost the one on live. Still having issues?

**Comment by paliaksvk** [comment]
Now it's working :)
I do not want it used for public purposes. It's just for me (I'm learning to program JS).
Thank you.
